alias adb "android adb"
alias free "env LANG=en_US.UTF-8 free -h"
alias ghc "stack exec -- ghc"
alias ghci "stack exec -- ghci"
alias less "less -R"
alias ls "ls --human-readable --group-directories-first --classify --color=auto --hyperlink=auto"
alias mypip "~/.local/bin/mypipenv/bin/pip"
alias mypipenv ". ~/.local/bin/mypipenv/bin/activate.fish"
alias tmux "tmux -2"
